name: 'Build and Push Bamserver Image to ACR'

on:
  workflow_dispatch:

env:
  ACR_NAME: fayaztest1
  ACR_REPO: fayaztest1.azurecr.io/fayaz-bamserver
  REGION: us-west-1
  ACR_USERNAME: fayaztest1
  ACR_PASSWORD: BWfvrlT1cUvWuZcYnD2fjQydFgwTUSSV5cSQ6miFam+ACRB4EfsF

jobs:
  build_and_deploy:
    name: 'Docker Image Creation'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Azure Container Registry Login
        run: |
          az acr login --name ${{ env.ACR_NAME }} --username ${{ env.ACR_USERNAME }} --password ${{ env.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./DockerFileFolder/Dockerfile
          tags: ${{ env.ACR_REPO }}:${{ github.ref_name }} 
